### ISSUE TITLE
Discrepancies with CustomHbondForce between Reference and CUDA platforms

### ISSUE THREAD

**Issue by mvanvleet** [pandegroup/openmm#1771]
CustomHbondForce is supposed to accept expressions which "may depend on arbitrary distances, angles, and dihedral angles of the particles involved in computing the force." When using the Reference platform, I have no problems including these distance(), angle(), or dihedral() functions in the .xml file for my force field, and the results agree with numbers I can obtain from other programs.

Upon switching to the CUDA platform, however, I get very different results for the distance() and dihedral() functions in particular. 

I've tried to provide an example of this behavior in the zip file below,

[dihedral_bug.zip](https://github.com/pandegroup/openmm/files/877329/dihedral_bug.zip)

which can be run with the command

```
$ python run_co2.py
```
and by changing the 'energy' expression in sapt_co2.xml and the platform in run_co2.py. For different energy expressions (listed below), which use the distance(), angle(), and dihedral() functions, I've summarized the resulting energies between the Reference and CUDA platforms. 

```
Energy Expression     Reference Platform      CUDA Platform
-------------------------------------------------------------------------
distance(a1,d1)               158244.998031         256944.557419
angle(d2,d1,a1)               332305.565796         332607.309815
dihedral(d3,d1,d2,a1)         16890.3384786         nan
```
 
For reference, I'm running these calculations on Tesla M2070 GPUs with CUDA 8.0 and version 7.1.0.dev-9567ddb of OpenMM.

These discrepancies between the two platforms are rather disconcerting, so any help diagnosing the underlying problem/bug would be most appreciated!

**Comment by mvanvleet** [comment]
In case this got lost amidst other issues, is there any update on what might be causing the discrepancies between platforms?

**Comment by mvanvleet** [comment]
@peastman , I'm extremely sorry to bother you in case you've already seen this and are working on other projects, but do you have any insight into what might be happening here?

**Comment by peastman** [comment]
Sorry, I just haven't had time to look into this yet.  I'll try to do it shortly.

**Comment by peastman** [comment]
I get an error when I try to open either of your files.  It looks like they're corrupt.  Can you check them?

**Comment by mvanvleet** [comment]
Sorry about that! I did change the file extension from .tgz to .zip so that github would allow me to upload it, and after testing on my linux partition you'll probably have to change the file extension back to .tgz before unpacking:

```
$ mv co2_dimer_nan_error.zip co2_dimer_nan_error.tgz
$ tar -xvf co2_dimer_nan_error.tgz
```

I can unzip both files on my machine just fine (I'm running MacOS), and had incorrectly assumed that changing the file extension would have no effect for other users.

**Comment by peastman** [comment]
That was the problem.  Thanks.

**Comment by peastman** [comment]
> my hunch is that dihedral() might be failing in edge cases where a subset of atoms form 90 and/or 180 degree angles.

It looks like that's exactly what's happening.  When the atoms are all in a line, the dihedral angle becomes undefined.  That means there's a discontinuity in the energy, and the force blows up as it approaches that point.

**Comment by mvanvleet** [comment]
Alright, that solves one source of the discrepancy between platforms. However, I'm still getting bizarrely specific mismatches between platforms, which I've tried to document in the following test case:

[co2_cuda_discrepancy.zip](https://github.com/pandegroup/openmm/files/904475/co2_cuda_discrepancy.zip)

(Again, it's really a .tgz file, not a .zip file, so you may have to rename the file extension before unzipping. The test in each subdirectory can be run via `$ bash test.sh` )

Here I'm using a test function that depends on one per donor/acceptor parameter (Aexch1) and one geometry-specific function (y101 = cos(angle(d2,d1,a1)) ). If I set either `energy=Aexch1` or `energy=y101`, the resulting energies agree between the CPU and CUDA platforms regardless of the value(s)of Aexch1. Furthermore, if I set `energy=Aexch1*y101` and all the per-donor parameters for Aexch1 agree for each atomtype, then the two platforms agree (see subdirectory 01). However, if I set `energy=Aexch1*y101` and use different values for the different per-donor parameters, then I get large disagreements between the two platforms (see subdirectory 02). I've benchmarked results from other codes against the CPU platform, so I'm fairly certain that something in the CUDA code is to blame here.

Thanks for the help, and let me know if I can be of assistance in sorting this out.

**Comment by peastman** [comment]
This is fixed by #1784.

**Comment by mvanvleet** [comment]
Perfect, thank you so much!

**Comment by mvanvleet** [comment]
I spoke too soon; I'm still finding discrepancies between platforms. Your bug fix works for the system I gave you, or for any system of two CO2 molecules that I have been able to test. However, as I move to larger systems, I suddenly start to see noticeable deviations between the two platforms. I've tried to include several different .pdb files for CO2, some of which provide identical energies, and others which have discrepancies. For example, a 4x4x4 cell of solid CO2 gives me the following energies:

```
CUDA
<simtk.openmm.openmm.CustomHbondForce; proxy of <Swig Object of type 'OpenMM::CustomHbondForce *' at 0x289d4b0> > -2821.80452844 kJ/mol
<simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x289d4e0> > 0.0 kJ/mol
<simtk.openmm.openmm.MonteCarloBarostat; proxy of <Swig Object of type 'OpenMM::MonteCarloBarostat *' at 0x289d390> > 0.0 kJ/mol
-2821.80452844 kJ/mol
----
CPU
<simtk.openmm.openmm.CustomHbondForce; proxy of <Swig Object of type 'OpenMM::CustomHbondForce *' at 0x21c9480> > -3804.1026135 kJ/mol
<simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x21c94b0> > 0.0 kJ/mol
<simtk.openmm.openmm.MonteCarloBarostat; proxy of <Swig Object of type 'OpenMM::MonteCarloBarostat *' at 0x21c9360> > 0.0 kJ/mol
-3804.1026135 kJ/mol
----
```

Other energies can be compared by copying over one of the .pdb files to co2.pdb and running

```bash
$ python run_co2.py CUDA; python run_co2.py CPU
```

The full set of test systems can be found here:

[large_system_bug_report.zip](https://github.com/pandegroup/openmm/files/924600/large_system_bug_report.zip)

As always, your time and help is much appreciated.

**Comment by mvanvleet** [comment]
Peter,

I'm still getting discrepancies between the two platforms. Can this issue be reopened?

**Comment by peastman** [comment]
Reopened.  I've managed to reproduce your results.  I'm still trying to track down the cause.

**Comment by peastman** [comment]
New PR posted: #1792.
