### ISSUE TITLE
Problems with explicit solvent MD and CUDA platform

### ISSUE THREAD

**Issue by danielparton** [pandegroup/openmm#926]
I've been running into problems running explicit-solvent MD simulations using the CUDA platform on our Linux cluster. My code attempts to run a series of 100 ps simulations, each of which normally takes ~5 mins to complete. The typical behavior is for ~5-10 simulations to complete, then one of thing two things happens:

1. the next simulation completes a few iterations, then fails with the following error message:
  
  ```
  File "/cbio/jclab/home/parton/opt/anaconda/lib/python2.7/site-packages/ensembler-0.2-py2.7.egg/ensembler/refinement.py", line 868, in simulate_explicit_md
    integrator.step(nsteps_per_iteration)
  File "/cbio/jclab/home/parton/opt/anaconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 12102, in step
    return _openmm.LangevinIntegrator_step(self, *args)
Exception: Error downloading array energyBuffer: Invalid error code (700)
```
2. the next simulation completes a few iterations, then hangs without producing further output.

I'm using the OpenMM 6.2 release, installed via conda.

We're currently looking into whether these errors might result from the cluster environment - e.g. since many of the nodes have not been rebooted for almost a year - but we wanted to post this issue here in case it merits further discussion.

**Comment by peastman** [comment]
What CUDA version are you using?

**Comment by jchodera** [comment]
I believe @danielparton is using CUDA 6.5 on a CentOS system with driver version 340.29.

**Comment by danielparton** [comment]
Correct

**Comment by jchodera** [comment]
For reference, that exception is thrown here:
https://github.com/pandegroup/openmm/blob/8b69b9c029f59ced3c9f02b3bd723702ec39d9c2/platforms/cuda/src/CudaArray.cpp#L77

**Comment by peastman** [comment]
Generally that means that you've got memory corruption on the GPU.  So that line doesn't give much information about how or when the problem originated.  Just that at some point before that, something went wrong.

**Comment by jchodera** [comment]
That's fine, but the problem is that the driver seems to be locking the GPU out of use on the next attempt to access it from another job:
```
  File "/cbio/jclab/home/parton/opt/anaconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 15302, in __init__
    this = _openmm.new_Context(*args)
Exception: Error initializing Context: CUDA_ERROR_INVALID_DEVICE (101) at /cbio/jclab/home/parton/opt/openmm/openmm/platforms/cuda/src/CudaContext.cpp:149
```
@danielparton : Is the `Context` object explicitly being deleted after catching this exception but before starting the next simulation?  I wonder if that might be the problem.

We should be sure to explicitly delete `Context` objects after use, since waiting for Python's automated `gc` to do this can tie up hardware resources.

**Comment by danielparton** [comment]
Actually, I haven't seen that particular error since we rebooted the node. (Although this could be related to the fact that I am now running jobs directly on the node, rather than via torque/moab.)

I still get the `Exception: Error downloading array energyBuffer: Invalid error code (700)` error intermittently, but it no longer seems to cause all subsequent simulations to fail with the `CUDA_ERROR_INVALID_DEVICE` error.

(to answer @jchodera's question, a new `Context` object is initialized at the start of each simulation)

The other major problem which is still occurring, however, is that a simulation occasionally hangs with no further output. I'm trying out a few tests at the moment - will update when I have news.

**Comment by jchodera** [comment]
> (to answer @jchodera's question, a new Context object is initialized at the start of each simulation)

That's not quite what I asked.  In order to not tie up hardware resources, we need to `del context` when we are done with the context, *even if we get an error*.

**Comment by swails** [comment]
e.g., via some `try: ... finally:` type of construct?

**Comment by danielparton** [comment]
Oh I see. No that wasn't being done. I'll add that in to the code now.

**Comment by peastman** [comment]
An even better solution might be to use the `multiprocessing` module to run each simulation in its own process.  That provides better isolation between contexts, and you can be more sure that everything was cleaned up.

**Comment by jchodera** [comment]
> An even better solution might be to use the multiprocessing module to run each simulation in its own process. That provides better isolation between contexts, and you can be more sure that everything was cleaned up.

We originally used that for parallelizing on a single node, but it's difficult to do this in a batch queue + MPI manner.

**Comment by jchodera** [comment]
Or were you suggesting just spawning one `multiprocessing` worker off of each MPI process?

**Comment by peastman** [comment]
The latter.  It's just a way to better isolate each context and make sure they get fully cleaned up.

**Comment by danielparton** [comment]
Just wanted to add that the `context` object is set within an inner simulation function, and should therefore be automatically cleaned up by the garbage collector once Python leaves that function scope (whether returning successfully or failing with an exception). So it would be kind of weird if the `del context` thing really made a difference. Although I guess things can get weird where GPUs are concerned.

@peastman thanks for the `multiprocessing` suggestion. Just wondering - have you encountered specific cases where this has helped?

**Comment by swails** [comment]
You're putting a lot of faith in the Python garbage collector :).  In particular, they make no guarantees about when it will run -- just that *when* it runs, objects with a reference count of zero (or equal to the number of inaccessible cyclical references) will get deallocated.

There's a bit of reference sharing and stealing going on behind-the-scenes in SWIG, so it's entirely possible that `del` has an actual effect (but I agree with you, it *shouldn't*).

**Comment by peastman** [comment]
When running the system test suite, I use multiprocessing to split each test into a separate process.  I've found it's the best way to make sure one failed test doesn't cause the whole suite to halt.

**Comment by danielparton** [comment]
Ok, thanks for the info @swails and @peastman!

**Comment by jchodera** [comment]
> Just wanted to add that the context object is set within an inner simulation function, and should therefore be automatically cleaned up by the garbage collector once Python leaves that function scope (whether returning successfully or failing with an exception)

I don't really think that's true.  I think Python is under no obligation to *immediately* clean up.  I've certainly run into problems here before.

**Comment by swails** [comment]
> I don't really think that's true. I think Python is under no obligation to immediately clean up. I've certainly run into problems here before.

This is true (as I've mentioned), but that remains true even after `del <blah>` is executed.  All `del <blah>` does is either call `__delitem__` when called on an element in a list or DECREF when called on an object.  It *could* alter the internal code path just enough to trigger a GC earlier, but that's just an implementation detail.

If you *really* wanted to be explicit, you'd have to import the `gc` module and explicitly garbage-collect.

**Comment by jchodera** [comment]
I've had good luck with `del`, but as @swails and @peastman point out, using `multiprocessing` to isolate the job in a separate process may be much safer.

**Comment by jchodera** [comment]
@pgrinaway may be interested in this conversation too.

**Comment by danielparton** [comment]
I've collected serialized system, state and integrator objects for two example simulation failures, and put them in this GitHub repo:
https://github.com/danielparton/openmm-model-debugging

There is also a script for repeatedly running test simulations from the deserialized files.

Further details in the `README.md` in that repo.

Note that the two failure types covered here are:
* simulation hangs without further output
* simulation emits Exception: `Error downloading array posq: Invalid error code (700)`

The `CUDA_ERROR_INVALID_DEVICE` error is not covered here, as that seems to be resolved by reloading the CUDA driver on our cluster.

If someone (@peastman?) could take a look at these models to try to work out what is actually going wrong, that would be much appreciated!

**Comment by jchodera** [comment]
@peastman: Would be awesome if you could take a look.  These issues---with either CUDA or OpenCL---have frustrated our attempts to scale up OpenMM simulations on a cluster.  Would be great if we could figure out what might be going on and if this could allow us to make OpenMM 6.3 much more robust.

**Comment by peastman** [comment]
Did you try using multiple processes like I suggested?  Did that not fix the problem?

**Comment by jchodera** [comment]
We're in the process of testing that too as a hacky workaround. Will report
on whether that works, but it would be great to see if we can make the
error handling robust enough to not leave the GPU in a weird unusable state.

**Comment by danielparton** [comment]
I think the multiprocessing idea was aimed at solving the `CUDA_ERROR_INVALID_DEVICE` problem - when testing, this seemed to have been resolved either by reloading the CUDA driver or by rebooting the cluster node. I will implement this at some point anyway, but haven't gotten round to it yet.

However, the main problem right now (as described in the first message in this thread) is that these simulations sometimes fail either by hanging with no further output, or with the error message `Exception: Error downloading array energyBuffer: Invalid error code (700)`. I think this is a different problem from the `CUDA_ERROR_INVALID_DEVICE` errors.

**Comment by peastman** [comment]
I'm currently running your test script in the "hanging" directory.  How long should I expect it to take for the error to happen?  It's currently on the fourth simulation with no problems so far.

The goal of using multiple processes is to make sure each context gets fully cleaned up before the next one starts.  The driver can only support a limited number of CUDA contexts at one time before it starts getting really unhappy and failing in a variety of ways.

**Comment by danielparton** [comment]
Thanks for running the test script!
The errors usually occur within the first 20 or so runs (often more like 6).

Ok, I guess it's possible that erroneous cleanup of CUDA context could be causing all of these errors - I'll try again with the `multiprocessing` approach soon.

**Comment by peastman** [comment]
It's on run 35 and still going.

**Comment by danielparton** [comment]
Ok, thanks. I've only tried these simulations on our cluster so far, so perhaps there is something wrong with the cluster environment. I'll try my test script out on some other machines.

Might be good to keep your test running until say 60 or 100 runs, but feel free to stop it earlier if it is a nuisance.

**Comment by peastman** [comment]
On run 92 and still going.  I'm going to stop it now.

**Comment by danielparton** [comment]
Sounds good, thanks.
I've tried the test simulations on our cluster using the CPU platform -
they run fine.
I'm about to try out the GPU platform on a different machine.

**Comment by jchodera** [comment]
I made it through 40 iterations on `gpu-2-7` (GTX-Titan with driver rev 340.29) before my interactive session ran out.  I'm using OpenMM version `6.3.0.dev-e6f38fe` (which should rougly correspond to the `openmm-dev` conda package).

**Comment by jchodera** [comment]
I've made it through 18 iterations of the `hanging` example with the standard `openmm` conda package on `gpu-2-5` (a GTX-680) machine.  No issues observed yet.

**Comment by danielparton** [comment]
Thanks for the additional info @jchodera 
The test script seems to be running successfully on the cluster using the CUDA platform now that I'm using the latest OpenMM dev version: `6.3.0.dev-50442b0`
Previously I was using the 6.2 release, installed via conda.

**Comment by jchodera** [comment]
I was able to get through 35 iterations of the `error-downloading-array-posq` without an exception being raised on `gpu-1-6` in the two-hour interactive session I ran using the standard `openmm` conda package (which should correspond to 6.2 release).  Maybe there is an issue with your environment on the cluster?

**Comment by danielparton** [comment]
The latest OpenMM dev version (`6.3.0.dev-50442b0`) is (mostly)* working fine for me now. I am guessing there was something wrong with my previous installation - I wonder if my Python installation was linking to a different version of the compiled code, but not certain.

\*Mostly, because I still get occasional `CUDA_ERROR_INVALID_DEVICE` errors - based on earlier tests, I think this would be resolved by either reloading the CUDA driver on our cluster nodes, or by restarting the nodes. We can discuss that in the relevant [issue thread](https://github.com/cBio/cbio-cluster/issues/258) on the cBio issue tracker.

**Comment by jchodera** [comment]
@danielparton were you still having errors here, or can this be closed?

**Comment by danielparton** [comment]
This is all resolved now. Closing.

**Comment by bmanubay** [comment]
@jchodera 

I think I'm having a similar issue to what was happening here. 

```
Traceback (most recent call last):
  File "run_molecule_101.01bar.py", line 105, in <module>
    simulation = Simulation(pdb.topology, system, integrator, platform, properties)
  File "/home/brma3379/anaconda3/envs/openff2/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/brma3379/anaconda3/envs/openff2/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 11936, in __init__
    this = _openmm.new_Context(*args)
Exception: Error initializing CUDA: CUDA_ERROR_INVALID_DEVICE (101)
```
The thing is that I'm only trying to initialize one `context` object per simulation and I've tried adding some lines of code to clear up anything lingering (with both `gc.collect()` and `del context, simulation`) before I try to create a new one, which seemed to work once, but it doesn't fix the issue. I haven't altered my conda distro at all since the issue starting happening sometime yesterday, so I'm not sure what the problem is. I'm working on the Lilac cluster as MSKCC.

**Comment by jchodera** [comment]
Tagging @Lnaden and @andrrizzi to make sure you have the latest LSF submission flags to make sure you get the right GPUs requested. Note that we're having trouble with LSF assigning multiple jobs to the same GPU, which may also be complicating this.

**Comment by jchodera** [comment]
Can you point me to your code @bmanubay ?

**Comment by bmanubay** [comment]
Here's the lsf script:
```
#!/bin/sh
#BSUB -J cychex_lj_vanilla
#BSUB -n 2
#BSUB -q gpuqueue
#BSUB -gpu "num=4:mode=exclusive_process"
#BSUB -W 05:00
#BSUB -o %J.stdout
#BSUB -eo %J.stderr
#BSUB -u brma3379@colorado.edu
#BSUB -B

cd $LS_SUBCWD
export OE_DIR=/home/brma3379/.OpenEye
export PATH=/home/brma3379/anaconda3/bin:$PATH
source activate openff2
module load cuda/9.0

python run_molecule.py cyclohexane C1CCCCC1 250 [#6X4:1] epsilon rmin_half 0.1094 1.9080 &
python run_molecule_101.01bar.py cyclohexane C1CCCCC1 250 [#6X4:1] epsilon rmin_half 0.1094 1.9080 &
```

**Comment by bmanubay** [comment]
Did you want the actual simulation code as well?

**Comment by bmanubay** [comment]
If so, here's the relevant bit:

```
#############################################################
# Simulation Parameters
#############################################################
kinetic_temperature = 293.15*kelvin
collision_frequency = 1./picosecond
step_size = 0.001*picoseconds

pressure = 1.01*bar
barostat_frequency = 1
#############################################################
#############################################################

system = forcefield.createSystem(pdb.topology,mols,nonbondedMethod=PME,nonbondedCutoff=1.2*nanometers)#,constraints=HBonds)

integrator = LangevinIntegrator(kinetic_temperature, collision_frequency, step_size)
barostat = MonteCarloBarostat(pressure, kinetic_temperature, barostat_frequency)
system.addForce(barostat)

#platform = mm.Platform.getPlatformByName('Reference')
#properties = {'None'}
platform = Platform.getPlatformByName('CUDA')
properties = {'CudaPrecision': 'mixed','DeterministicForces': 'true'}

simulation = Simulation(pdb.topology, system, integrator, platform, properties)
simulation.context.setPositions(pdb.positions)
simulation.context.setVelocitiesToTemperature(kinetic_temperature)
simulation.minimizeEnergy()
```

**Comment by Lnaden** [comment]
@jchodera is right, I would be willing to bet this is a lilac problem (MSKCC's LSF cluster) assigning the same GPU even though its not suppose to be. We have a ticket open with the support here, so this may not be an OpenMM problem. Will keep you updated

**Comment by bmanubay** [comment]
That’s what I had thought. Thanks @Lnaden!

**Comment by bmanubay** [comment]
@Lnaden @jchodera The problem seems to have cleared up. I haven't had any trouble since early yesterday morning. Don't know what you've heard from HPC IT, but I've been able to run plenty of simulations without any hang-ups

**Comment by Lnaden** [comment]
Glad to hear. They fixed the oversubscription problem, but the GPU modes are still not being set correctly. If something comes up w.r.t. the cluster, feel free to email/slack us as I dont think debugging our cluster here is the best medium. If it does turn out to be something OpenMM related, we can re-visit the issue

**Comment by bmanubay** [comment]
Sweet! Thanks Levi!
